version: '3.8'
services:
  api:
    container_name: api-lotr
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/app
  db:
    container_name: database-lotr
    image: postgres:latest
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes: 
 data: {}